// Auto-generated by UIAddressableKeysGenerator
// Do not modify manually

using System.Collections.Generic;

public static class UIAddressableKeys
{
    private static readonly Dictionary<string, string> Keys = new()
    {
        { "UIBlocker", "Assets/_Project/Prefab/UI/Common/UIBlocker.prefab" },
        { "UIBossWarningPanel", "Assets/_Project/Prefab/UI/InGame/UIBossWarningPanel.prefab" },
        { "UIIAPPurchaseSuccessPopup", "Assets/_Project/Prefab/UI/Common/UIIAPPurchaseSuccessPopup.prefab" },
        { "UIInGameMain", "Assets/_Project/Prefab/UI/InGame/UIInGameMain.prefab" },
        { "UILoadingOverPopup", "Assets/_Project/Prefab/UI/Common/UILoadingOverPopup.prefab" },
        { "UILobbyMain", "Assets/_Project/Prefab/UI/Lobby/UILobbyMain.prefab" },
        { "UITitle", "Assets/_Project/Prefab/UI/UITitle.prefab" },
        { "UIWaveStarter", "Assets/_Project/Prefab/UI/InGame/UIWaveStarter.prefab" },
    };

    public static string Get<T>() => Keys.TryGetValue(typeof(T).Name, out var key) ? key : null;
    public static string Get(string typeName) => Keys.TryGetValue(typeName, out var key) ? key : null;
}
