using UnityEngine;
using UnityEditor;
using UnityEditor.AddressableAssets;
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

public static class UIAddressableKeysGenerator
{
    private const string OutputPath = "Assets/SCG/Scripts/UI/UIAddressableKeys.cs";

    [MenuItem("SCG/Tools/Generate/Generate UI Addressable Keys")]
    public static void Generate()
    {
        try
        {
            EditorUtility.DisplayProgressBar("Generate UI Addressable Keys", "Scanning prefabs...", 0.2f);

            var entries = new List<(string typeName, string addressableKey)>();

            // Find all prefabs
            var prefabGuids = AssetDatabase.FindAssets("t:Prefab");

            foreach (var guid in prefabGuids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (prefab == null) continue;

                // Check all components on the prefab root that inherit from UIBase
                var components = prefab.GetComponents<UIBase>();
                foreach (var component in components)
                {
                    if (component == null) continue;
                    var componentType = component.GetType();

                    // Skip UIBase itself
                    if (componentType == typeof(UIBase)) continue;

                    // Get Addressable key
                    var addressableKey = GetAddressableKey(path);
                    if (!string.IsNullOrEmpty(addressableKey))
                    {
                        entries.Add((componentType.Name, addressableKey));
                    }
                    else
                    {
                        Debug.LogWarning($"[UIAddressableKeys] Prefab '{path}' with component '{componentType.Name}' is not Addressable.");
                    }
                }
            }

            if (entries.Count == 0)
            {
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("UIAddressableKeys", "No Addressable prefabs with UIBase components found.", "OK");
                return;
            }

            EditorUtility.DisplayProgressBar("Generate UI Addressable Keys", "Generating code...", 0.8f);

            GenerateCode(entries);

            EditorUtility.ClearProgressBar();
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog("UIAddressableKeys",
                $"Generated {entries.Count} addressable key(s).\nPath: {OutputPath}", "OK");
        }
        catch (Exception e)
        {
            EditorUtility.ClearProgressBar();
            Debug.LogError($"[UIAddressableKeys] Generation failed: {e}");
            EditorUtility.DisplayDialog("Error", "Generation failed. Check Console.", "OK");
        }
    }

    private static string GetAddressableKey(string assetPath)
    {
        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
        {
            Debug.LogError("[UIAddressableKeys] Addressable settings not found.");
            return null;
        }

        var guid = AssetDatabase.AssetPathToGUID(assetPath);

        // includeImplicit: true - 폴더로 등록된 에셋도 찾음
        var entry = settings.FindAssetEntry(guid, true);

        // Debug: 왜 못 찾는지 확인
        if (entry == null)
        {
            Debug.Log($"[UIAddressableKeys] Debug - Path: {assetPath}, GUID: {guid}, Entry: null");
        }

        return entry?.address;
    }

    private static void GenerateCode(List<(string typeName, string addressableKey)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by UIAddressableKeysGenerator");
        sb.AppendLine("// Do not modify manually");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("public static class UIAddressableKeys");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, string> Keys = new()");
        sb.AppendLine("    {");

        // Sort by type name for consistent output
        entries.Sort((a, b) => string.Compare(a.typeName, b.typeName, StringComparison.Ordinal));

        foreach (var (typeName, addressableKey) in entries)
        {
            sb.AppendLine($"        {{ \"{typeName}\", \"{addressableKey}\" }},");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static string Get<T>() => Keys.TryGetValue(typeof(T).Name, out var key) ? key : null;");
        sb.AppendLine("    public static string Get(string typeName) => Keys.TryGetValue(typeName, out var key) ? key : null;");
        sb.AppendLine("}");

        // Ensure directory exists
        var directory = Path.GetDirectoryName(OutputPath);
        if (!Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        File.WriteAllText(OutputPath, sb.ToString());
        Debug.Log($"[UIAddressableKeys] Generated: {OutputPath}");
    }
}